### ISSUE TITLE
Short term roadmap

### ISSUE THREAD

**Issue by HashimotoYT** [siberianmh/vscode-github#1]
- [ ] Increase logging support
- [ ] Ensure comments provider are additive
- [ ] Investigate how active source control provider can control what's visible in the PR viewlets
- [ ] Ensure cross-platform support
- [ ] Publish preview in Marketplace
- [ ] Setup CI
- [ ] Investigate alternatives for multi-vendor story;
- Architecture
	- [ ] Ensure clear auth separation
 	- [ ] Basic auth tests
	- [ ] Ensure clear model separation
	- [ ] Basic model tests
